[package]
name = "needle-desktop"
version.workspace = true
edition.workspace = true
publish.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
needle-core = { workspace = true }
needle-vault = { workspace = true }
needle-vcs = { workspace = true }
serde = { workspace = true }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tempfile = "3"
