[package]
name = "needle-desktop-ui"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
console_error_panic_hook = "0.1"
js-sys = "0.3"
leptos = { version = "0.8", features = ["csr"] }
needle-core = { workspace = true }
serde = { workspace = true }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["DataTransfer", "Document", "DomRect", "DomRectList", "DragEvent", "Element", "HtmlElement", "Location", "PointerEvent", "WheelEvent", "ScrollIntoViewOptions", "ScrollLogicalPosition", "Storage", "Window"] }
